import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/navbar/Header";
import ModalProvider from "@/components/ModalProvider";
import { Toaster } from "@/components/ui/toaster";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:
    "Airbnb | Vacation Rentals, Cabins, Beach Houses, Unique Homes & Experiences",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            font.className,
            "min-h-screen flex flex-col antialiased"
          )}
          suppressHydrationWarning
        >
          <Header />
          <ModalProvider />
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
