import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/navbar/Header";
import ModalProvider from "@/components/ModalProvider";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:
    "Airbnb | Vacation Rentals, Cabins, Beach Houses, Unique Homes & Experiences",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(font.className, "min-h-screen flex flex-col antialiased")}
        suppressHydrationWarning
      >
        <Header />
        <ModalProvider />
        {children}
      </body>
    </html>
  );
}
